from tkinter import *

window = Tk()
window.geometry('360x220')
window.title('password')
window.resizable(False, False)

# sym = Frame( width=250, height=250, relief=RIDGE, bg='#ABB1E1')
# sym.pack(expand=True)
lowercase = BooleanVar()
numbers = BooleanVar()
uppercase = BooleanVar()
signs = BooleanVar()
op1 = Checkbutton(text='qwertyuiopasdfghjklzxcvbnm', variable=lowercase, offvalue=False, onvalue=True, anchor='w', pady=5)
op1.grid(row=0, column=0, sticky='w')
op2 = Checkbutton(text='0123456789', variable=numbers, offvalue=False, onvalue=True, anchor='w', pady=5)
op2.grid(row=1, column=0, sticky='w')
op3 = Checkbutton(text='QWERTYUIOPASDFGHJKLZXCVBNM', variable=uppercase, offvalue=False, onvalue=True, anchor='w', pady=5)
op3.grid(row=2, column=0, sticky='w')
op4 = Checkbutton(text='!@#$%^&*()', variable=signs, offvalue=False, onvalue=True, anchor='w', pady=5)
op4.grid(row=3, column=0, sticky='w')
spnlc = Spinbox(from_=1, to_=8, state='readonly')
spnlc.grid(row=0, column=1)
spnnum = Spinbox(from_=1, to_=8, state='readonly')
spnnum.grid(row=1, column=1)
spnup = Spinbox(from_=1, to_=8, state='readonly')
spnup.grid(row=2, column=1)
spnsn = Spinbox(from_=1, to_=8, state='readonly')
spnsn.grid(row=3, column=1)
enrt = Entry()
enrt.grid(row=4, column=0, columnspan=2)
bt1 = Button(text='generate a password', width=30, pady=5)
bt1.grid(row=5, column=0, columnspan=2)

lbl_safety = Label(window, text="Safety: ---", font=("Arial", 10, "bold"), pady=5)
lbl_safety.grid(row=6, column=0, columnspan=2)

# window.mainloop()
